title: Chase Lemons # your name (or website title) here
logo: "/images/Professional Pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is my portfolio for the last class in Bellevue Universities Data Science Program.
  <br><br>
  <a href="https://www.linkedin.com/in/chase-lemons-5507b2b7/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
